SET NAMES utf8mb4;

CREATE TABLE country (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NULL, alpha2 CHAR(2) NOT NULL, alpha3 CHAR(3) NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, UNIQUE KEY uq_country_alpha2 (alpha2), UNIQUE KEY uq_country_external_id (external_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE city (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NULL, country_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(150) NULL, CONSTRAINT fk_city_country FOREIGN KEY (country_id) REFERENCES country(id), UNIQUE KEY uq_city_external_id (external_id), UNIQUE KEY uq_city_country_name (country_id, name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE competition (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NULL, country_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(150) NOT NULL, gender CHAR(1) NULL, competition_type VARCHAR(50) NULL, tier INT NULL, image VARCHAR(255) NULL, primary_color CHAR(7) NULL, secondary_color CHAR(7) NULL, CONSTRAINT fk_competition_country FOREIGN KEY (country_id) REFERENCES country(id), UNIQUE KEY uq_competition_external_id (external_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE competition_season (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NULL, competition_id BIGINT UNSIGNED NOT NULL, year SMALLINT NOT NULL, number_of_competitors SMALLINT NULL, CONSTRAINT fk_season_competition FOREIGN KEY (competition_id) REFERENCES competition(id), UNIQUE KEY uq_competition_season (competition_id, year), UNIQUE KEY uq_season_external_id (external_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE venue (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NOT NULL, city_id BIGINT UNSIGNED NULL, name VARCHAR(200) NOT NULL, slug VARCHAR(200) NULL, capacity INT UNSIGNED NULL, latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, image VARCHAR(255) NULL, CONSTRAINT fk_venue_city FOREIGN KEY (city_id) REFERENCES city(id), UNIQUE KEY uq_venue_external_id (external_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NOT NULL, country_id BIGINT UNSIGNED NULL, venue_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(100) NULL, full_name VARCHAR(150) NULL, slug VARCHAR(150) NULL, name_code VARCHAR(10) NULL, gender CHAR(1) NULL, primary_color CHAR(7) NULL, secondary_color CHAR(7) NULL, text_color CHAR(7) NULL, image VARCHAR(255) NULL, foundation_date DATE NULL, CONSTRAINT fk_team_country FOREIGN KEY (country_id) REFERENCES country(id), CONSTRAINT fk_team_venue FOREIGN KEY (venue_id) REFERENCES venue(id), UNIQUE KEY uq_team_external_id (external_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE competition_team (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, competition_season_id BIGINT UNSIGNED NOT NULL, team_id BIGINT UNSIGNED NOT NULL, CONSTRAINT fk_ct_season FOREIGN KEY (competition_season_id) REFERENCES competition_season(id), CONSTRAINT fk_ct_team FOREIGN KEY (team_id) REFERENCES team(id), UNIQUE KEY uq_competition_team (competition_season_id, team_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE competition_winner (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, competition_season_id BIGINT UNSIGNED NOT NULL, team_id BIGINT UNSIGNED NOT NULL, CONSTRAINT fk_cw_season FOREIGN KEY (competition_season_id) REFERENCES competition_season(id), CONSTRAINT fk_cw_team FOREIGN KEY (team_id) REFERENCES team(id), UNIQUE KEY uq_competition_winner (competition_season_id, team_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE team_title (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, team_id BIGINT UNSIGNED NOT NULL, competition_id BIGINT UNSIGNED NOT NULL, competition_season_id BIGINT UNSIGNED NULL, CONSTRAINT fk_tt_team FOREIGN KEY (team_id) REFERENCES team(id), CONSTRAINT fk_tt_competition FOREIGN KEY (competition_id) REFERENCES competition(id), CONSTRAINT fk_tt_season FOREIGN KEY (competition_season_id) REFERENCES competition_season(id), UNIQUE KEY uq_team_title (team_id, competition_id, competition_season_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE person (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, external_id BIGINT UNSIGNED NOT NULL, country_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(100) NULL, slug VARCHAR(150) NULL, birth_date DATE NULL, deceased BOOLEAN NOT NULL DEFAULT FALSE, image VARCHAR(255) NULL, CONSTRAINT fk_person_country FOREIGN KEY (country_id) REFERENCES country(id), UNIQUE KEY uq_person_external_id (external_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player (id BIGINT UNSIGNED PRIMARY KEY, height SMALLINT NULL, preferred_foot VARCHAR(20) NULL, position VARCHAR(10) NULL, proposed_market_value DECIMAL(15,2) NULL, proposed_market_currency CHAR(3) NULL, CONSTRAINT fk_player_person FOREIGN KEY (id) REFERENCES person(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE manager (id BIGINT UNSIGNED PRIMARY KEY, nationality VARCHAR(100) NULL, nationality_iso2 CHAR(2) NULL, preferred_formation VARCHAR(30) NULL, CONSTRAINT fk_manager_person FOREIGN KEY (id) REFERENCES person(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_team_period (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, player_id BIGINT UNSIGNED NOT NULL, team_id BIGINT UNSIGNED NOT NULL, start_at DATETIME NULL, end_at DATETIME NULL, CONSTRAINT fk_ptp_player FOREIGN KEY (player_id) REFERENCES player(id), CONSTRAINT fk_ptp_team FOREIGN KEY (team_id) REFERENCES team(id), UNIQUE KEY uq_current_player_team (player_id, team_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE manager_team_period (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, manager_id BIGINT UNSIGNED NOT NULL, team_id BIGINT UNSIGNED NOT NULL, start_at DATETIME NULL, end_at DATETIME NULL, CONSTRAINT fk_mtp_manager FOREIGN KEY (manager_id) REFERENCES manager(id), CONSTRAINT fk_mtp_team FOREIGN KEY (team_id) REFERENCES team(id), UNIQUE KEY uq_current_manager_team (manager_id, team_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_attribute_overview (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, player_id BIGINT UNSIGNED NOT NULL, year_shift TINYINT NOT NULL, position VARCHAR(10) NULL, attacking TINYINT NULL, technical TINYINT NULL, tactical TINYINT NULL, defending TINYINT NULL, creativity TINYINT NULL, CONSTRAINT fk_pao_player FOREIGN KEY (player_id) REFERENCES player(id), UNIQUE KEY uq_player_attribute_overview (player_id, year_shift, position)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE player_statistics_snapshot (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, player_id BIGINT UNSIGNED NOT NULL, source_index SMALLINT UNSIGNED NOT NULL, statistic_type VARCHAR(30) NOT NULL, payload JSON NOT NULL, CONSTRAINT fk_pss_player FOREIGN KEY (player_id) REFERENCES player(id), UNIQUE KEY uq_player_statistics_snapshot (player_id, source_index)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
