import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import mysql from "mysql2";
import type { Pool, RowDataPacket } from "mysql2/promise";

const tables = [
  // Base
  "country",
  "city",

  // Competitions
  "competition",
  "competition_season",
  "competition_season_host_country",

  // Venues / teams
  "venue",
  "team",

  // Competition relations
  "competition_team",
  "competition_winner",
  "competition_season_newcomer_upper",
  "competition_season_newcomer_lower",
  "team_title",

  // People
  "person",
  "player",
  "player_position",
  "manager",

  // Careers
  "player_team_period",
  "manager_team_period",
  "manager_performance",
  "manager_attributes",

  // Player data
  "player_attribute_overview",
  "player_statistics_snapshot",
  "player_match_rating",

  // Competition metadata
  "competition_other_name",
  "tv_partner",
  "competition_tv_partner",
  "organization",
  "competition_organization",
  "competition_season_promotion",
] as const;

const rowValue = (value: unknown): string => {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (value instanceof Date) {
    return mysql.escape(
      value
        .toISOString()
        .slice(0, 19)
        .replace("T", " "),
    );
  }

  if (typeof value === "object") {
    return mysql.escape(JSON.stringify(value));
  }

  return mysql.escape(
    value as string | number | boolean,
  );
};

export class Exporter {
  constructor(
    private readonly pool: Pool,
  ) {}

  async write(
    outputPath = path.resolve(
      process.cwd(),
      "exports",
      "brasileirao.mysql",
    ),
  ): Promise<void> {
    const schemaPath = path.resolve(
      process.cwd(),
      "src/database/migrations/001_initial.sql",
    );

    const schema = await readFile(
      schemaPath,
      "utf8",
    );

    const chunks: string[] = [
      "-- Generated by football-data-maker. Do not edit manually.\n",
      "SET FOREIGN_KEY_CHECKS=0;\n\n",
      schema.trim(),
      "\n\n",
    ];

    for (const table of tables) {
      const [rows] = await this.pool.query<RowDataPacket[]>(
        `
          SELECT *
          FROM \`${table}\`
          ORDER BY id
        `,
      );

      if (!rows.length) {
        continue;
      }

      const columns = Object.keys(rows[0] ?? {});

      chunks.push(
        `INSERT INTO \`${table}\` (${columns
          .map((column) => mysql.escapeId(column))
          .join(", ")}) VALUES\n`,
      );

      chunks.push(
        rows
          .map(
            (row) =>
              `(${columns
                .map((column) => rowValue(row[column]))
                .join(", ")})`,
          )
          .join(",\n"),
      );

      chunks.push(";\n\n");
    }

    chunks.push(
      "SET FOREIGN_KEY_CHECKS=1;\n",
    );

    await mkdir(
      path.dirname(outputPath),
      {
        recursive: true,
      },
    );

    await writeFile(
      outputPath,
      chunks.join(""),
      "utf8",
    );
  }
}