import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import mysql from "mysql2";
import type { Pool } from "mysql2/promise";
import type { RowDataPacket } from "mysql2";

const tables = [
  "country",
  "city",
  "competition",
  "competition_season",
  "venue",
  "team",
  "competition_team",
  "competition_winner",
  "team_title",
  "person",
  "player",
  "manager",
  "player_team_period",
  "manager_team_period",
  "player_attribute_overview",
  "player_statistics_snapshot"
];

const rowValue = (value: unknown): string => {
  if (value === null || value === undefined) return "NULL";
  if (value instanceof Date) return mysql.escape(value.toISOString().slice(0, 19).replace("T", " "));
  if (typeof value === "object") return mysql.escape(JSON.stringify(value));
  return mysql.escape(value as string | number | boolean);
};

export class Exporter {
  constructor(private readonly pool: Pool) {}

  async write(outputPath = path.resolve(process.cwd(), "exports", "brasileirao.mysql")): Promise<void> {
    const schema = await readFile(path.resolve(process.cwd(), "src/database/migrations/001_initial.sql"), "utf8");
    const chunks = ["-- Generated by football-data-maker. Do not edit manually.\n", "SET FOREIGN_KEY_CHECKS=0;\n", schema.trim(), "\n"];
    for (const table of tables) {
      const [rows] = await this.pool.query<RowDataPacket[]>(`SELECT * FROM \`${table}\` ORDER BY id`);
      if (!rows.length) continue;
      const columns = Object.keys(rows[0] ?? {});
      chunks.push(`INSERT INTO \`${table}\` (${columns.map((column) => mysql.escapeId(column)).join(", ")}) VALUES\n`);
      chunks.push(rows.map((row) => `(${columns.map((column) => rowValue(row[column])).join(", ")})`).join(",\n"));
      chunks.push(";\n");
    }
    chunks.push("SET FOREIGN_KEY_CHECKS=1;\n");
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, chunks.join(""), "utf8");
  }
}
